export const RECEIVE_RECIPT_DATA = 'RECEIVE_RECIPT_DATA';
export const RECEIVED_AVALIBLE_COM_PORTS = 'RECEIVED_AVALIBLE_COM_PORTS';
export const ACTUAL_FISCAL_PRINTER_SIMULATOR_STATE = 'ACTUAL_FISCAL_PRINTER_SIMULATOR_STATE';

export const CONNECT_TO_COM_PORT_SUCCESS = 'CONNECT_TO_COM_PORT_SUCCESS';
export const CONNECT_TO_COM_PORT_FAILED = 'CONNECT_TO_COM_PORT_FAILED';

export const DISCONNECT_FROM_COM_SUCCESS = 'DISCONNECT_FROM_COM_SUCCESS';
export const DISCONNECT_FROM_COM_FAILED = 'DISCONNECT_FROM_COM_FAILED';

export const ACTUAL_TRANSLATION_FOR_SIMULATOR_CLIENT = 'ACTUAL_TRANSLATION_FOR_SIMULATOR_CLIENT';